* Justification For Existence Of This Project

Share links to Emacs initialization files with minimal effort!

I love reading all kinds of Emacs configuration files ranging for super
refined to just starting out. For example [[https://github.com/caisah/emacs.dz][caisah]] has a list of loads of
stellar examples. However the only way to get added to that list is for your
configuration to be notable. That is a pretty high bar for people just
starting out. New people also usually have the freshest ideas though and they
challenge the status quo of what we currently consider "the best". All of
those perspectives are valuable so I wanted to create a simple list that can
include all of them.

The only requirement for adding a link here is that you or someone else values
it. A lot or a little no matter how much—someone just needs to have found it
valuable. No shyness or self-consciousness allowed: absolutely add your own! 😄

Emacs is about sharing and learning and that includes the entire spectrum of
code out there. Happy Hacking!

* How To Contribute

- Steps
  - Identify Emacs initialization files that either you or someone else found
    valuable in some way no matter how large or small.
  - Find a link where to get the configuration. That would be a link to the
    Git project containing it, the file itself, or a blog post. It is at your
    discretion.
  - Add that link here.

* Keep It Simple

The links are stored as headlines—that way you can store as little or as much
information as you like in whatever way that you want. Add notes, comments,
attribution, and any other classifications of anything. You can apply Org
tags, properties, etc. here. Utilize everything that Org has to offer. Think
of their headline as the most important note to leave for the future reader,
and that includes unforeseen ways that they might want to /use/ the metadata
too!

* Initialization Files

** Aaron Bedra

[[http://aaronbedra.com/emacs.d/][Aaron Bedra's Emacs 26 Configuration]]

** Donald Curtis

[[https://github.com/milkypostman/dotemacs][Personal .emacs.d directory]]

** Magnar Sveen

[[https://github.com/magnars/.emacs.d][My emacs settings]]

** neptune_speed

[[https://gitgud.io/neptune_speed/init_el/tree/master][Init_El]]

** Sacha Chua

[[http://pages.sachachua.com/.emacs.d/Sacha.html][Sacha Chua's Emacs configuration]]

** Steve Purcell

[[https://github.com/purcell/emacs.d][A reasonable Emacs config]]
